name: Hourly Useless Commit

on:
  schedule:
    # Run the workflow every hour
    - cron: "0 * * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make a trivial change
      - name: Make a meaningless change
        run: |
          echo "Last updated: $(date)" > useless.txt

      # Step 3: Configure git
      - name: Configure git
        run: |
          git config user.name "Jens Schäfer"
          git config user.email "jens-schaefer@outlook.com"

      # Step 4: Commit and push the change
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add useless.txt
          git commit -m "Useless commit: $(date)"
          git push

