name: Hourly Useless Commit

on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "Jens Schäfer"
          git config user.email "jens-schaefer@outlook.com"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in {1..5}; do
            echo "Making commit #$i"
            echo "Last updated: $(date)" > useless.txt
            git add useless.txt
            git commit -m "Useless commit #$i: $(date)"
            git push
            sleep 1 # Optional: avoid race conditions in case of rapid commits
          done
